name: DTE Action Metrics
description: This action will collect metrics from the other actions that utilize it
author: Mohamed El-Malah

inputs:
  action_name:
    description: Name of calling action
    required: true
  start_time:
    description: Time action started
    required: true
  action_url:
    description: URL for ADX service
    required: true

runs:
  using: 'composite'

  steps:
    - name: Echo Action
      run: |
        echo "Capturing metrics for action: ${action_name} and sending to ADX"
      shell: bash
      
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    # This is needed to determine the path to the github action. 
    # The path that is inherited from the runner is not correct if the action is running in a container
    - name: Set Action Environment
      id: runner-path
      run: |
        if [[ "${{github.action_path}}" == *"$PWD"* ]] 
        then
          echo "Path is running on runner"
          echo ::set-output name=action-path::${{github.action_path}}
        else
          echo "action is running in container"
          echo ::set-output name=action-path::"$PWD/.github/actions/dte-action-metrics"
        fi
      shell: bash
      
    - name: print path
      run: echo ${{steps.runner-path.outputs.action-path}}
      shell: bash

    - name: Get action metrics
      id: metrics
      env:
        GH_TOKEN: ${{ github.token }}
        ACTION_NAME: ${{ inputs.action_name }}
        START_TIME: ${{ inputs.start_time }}
        ACTION_URL: ${{ inputs.action_url }}
      run: |
        node ${{steps.runner-path.outputs.action-path}}/dist/index.js || true
      shell: bash
