name: DTE Action Metrics
description: This action will collect metrics from the other actions that utilize it
author: Mohamed El-Malah

inputs:
  action_name:
    description: Name of calling action
    required: true
  start_time:
    description: Time action started
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'