name: DTE Action Metrics
description: This action will collect metrics from the other actions that utilize it
author: Mohamed El-Malah

inputs:
  action_name:
    description: Name of calling action
    required: true
  start_time:
    description: Time action started
    required: true

runs:
  using: 'composite'

  steps:
    - name: Check token
      id: token
      run: |
        echo "Checking token"
        echo echo ::set-output name=GH_TOKEN::${{github.token}}
      shell: bash

    - name: Get action metrics
      id: metrics
      env:
        GH_TOKEN: ${{ steps.token.outputs.GH_TOKEN }}
      run: |
        node ${{ github.action_path }}/dist/index.js
      shell: bash